blank_issues_enabled: true
contact_links:
  - name: Workshop Curriculum Repository
    url: https://github.com/Community-Access/git-going-with-github
    about: Use this for curriculum and platform changes.
  - name: Learning Room Template Repository
    url: https://github.com/Community-Access/learning-room-template
    about: Use this for template-specific workflow and content updates.
